apiVersion: v1
kind: Service
metadata:
  name: inisvc-clusterip
  #namespace: jhdigital-gateway-services
spec:
  type: NodePort
  selector:
    app: inisvc
  ports:
    - port: 5211 #80
      targetPort: 52001
      nodePort: 30911