apiVersion: v1
kind: Service
metadata:
  name: inisvc1-nodePort
  namespace: jhdigital-gateway-services
spec:
  type: NodePort
  selector:
    app: inisvc1
  ports:
    - port: 80 #5211
      targetPort: 52101
      nodePort: 30921